version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  giropops-senhas:
    build:
      context: .
      dockerfile: Dockerfile
    image: johnmonteir0/linuxtips-giropops-senhas:1.0
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis  # Use the service name as the hostname
    depends_on:
      - redis

