services:
  redis:
    image: johnmonteir0/chainguard-redis:latest
    ports:
      - "6379:6379"
    volumes:
      - strigus:/strigus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  giropops-senhas:
    build:
      context: .
      dockerfile: Dockerfile
    image: johnmonteir0/linuxtips-giropops-senhas:2.0
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis

    volumes:
      - strigus:/strigus
    depends_on:
      - redis
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.63
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP (not used here, but handy)
      - "14250:14250"  # Jaeger gRPC (collector)
      - "14268:14268"  # Jaeger HTTP
      - "14269:14269"

volumes:
  strigus:
