services:
  redis:
    image: johnmonteir0/chainguard-redis:latest
    ports:
      - "6379:6379"

  giropops-senhas:
    build:
      context: .
      dockerfile: Dockerfile
    image: johnmonteir0/linuxtips-giropops-senhas:2.0
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis  # Use the service name as the hostname
    volumes:
      - strigus:/strigus # Build Volume
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M
    depends_on:
      - redis

volumes:
  strigus: