{{- range $component, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $component "redis" }}
  name: redis-service
  {{- else }}
  name: {{ $component }}
  {{- end }}
  labels:
    {{- include "app.labels" $config | nindent 4 }}
spec:
  type: {{ $config.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $config.labels.app | default $component }}
  ports:
    {{- toYaml $config.ports | nindent 4 }}
{{- end }}
