{{- range $component, $config := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component }}
  labels:
    {{- include "app.labels" $config | nindent 4 }}
spec:
  replicas: {{ $config.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ $config.labels.app }}
  template:
    metadata:
      labels:
        {{- include "app.labels" $config | nindent 8 }}
    spec:
      containers:
        - name: {{ $component }}
          image: {{ $config.image }}
          ports:
            {{- include "app.ports" $config | nindent 12 }}
          {{- if $config.env }}
          env:
            {{- range $env := $config.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
          {{- end }}
          {{- if $config.resources }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          {{- end }}
          {{- if $config.volumeMounts }}
          volumeMounts:
            {{- toYaml $config.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if $config.volumes }}
      volumes:
        {{- toYaml $config.volumes | nindent 8 }}
      {{- end }}
---
{{- end }}


