deployments:
  giropops-senhas:
    name: "giropops-senhas"
    image: "johnmonteir0/linuxtips-giropops-senhas:6.0"
    replicas: 3
    ports:
      - port: 5000
        targetPort: 5000
        name: "giropops-senhas-port"
        NodePort: 32500
      - port: 8088
        targetPort: 8088
        name: "giropops-senhas-metrics"
    labels:
      app: "giropops-senhas"
      env: "labs"
    resources:
      requests: { memory: "128Mi", cpu: "250m" }
      limits:   { memory: "256Mi", cpu: "500m" }

    # >>> Run via auto-instrumentation wrapper <<<
    command: ["/bin/sh","-lc"]
    args:
      - >
        opentelemetry-instrument
        --traces_exporter otlp
        --metrics_exporter none
        --service_name giropops-senhas
        python app.py

    env:
      # Identity & verbosity
      - name: OTEL_LOG_LEVEL
        value: "info"
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=labs"

      # Send OTLP *directly to Jaeger* over HTTP/protobuf (4318)
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://jaeger-collector.giropops-senhas.svc.cluster.local:4318"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"

  redis:
    image: "johnmonteir0/chainguard-redis"
    replicas: 1
    port: 6379
    labels: { app: "redis", env: "labs" }
    resources:
      requests: { memory: "128Mi", cpu: "250m" }
      limits:   { memory: "256Mi", cpu: "500m" }

# Collector is no longer needed — removed

services:
  giropops-senhas:
    ports:
      - port: 5000
        targetPort: 5000
        name: "app"
        serviceType: "ClusterIP"
      - port: 8088
        targetPort: 8088
        name: "metrics"
        serviceType: "ClusterIP"
    labels: { app: "giropops-senhas", env: "labs" }

  redis:
    ports:
      - port: 6379
        targetPort: 6379
        name: "service"
        serviceType: "ClusterIP"
    labels: { app: "redis", env: "labs" }

# Entire "observability: otel-collector-config" section removed

databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"

monitoring:
  enabled: true
  serviceMonitors:
    # Keep only the app's ServiceMonitor (Collector one removed)
    - name: giropops-senhas
      namespace: giropops-senhas
      labels: { app: giropops-senhas, env: labs }
      prometheusRelease: kube-prometheus-stack
      selector:
        matchLabels:
          app: giropops-senhas
      targetNamespace: giropops-senhas
      endpoints:
        - port: metrics
          path: /metrics
          interval: 30s
          scrapeTimeout: 10s
