name: "Application: Pipeline"

on:
  push:
    branches: [ main, staging, stg/*, develop, dev/* ]
    paths:
      - 'app.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/app.yml'
      - 'kubernetes/chart/**'
  workflow_dispatch: {}

env:
  IMAGE_NAME: johnmonteir0/linuxtips-giropops-senhas

permissions:
  contents: read
  id-token: write

concurrency:
  group: app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------------------------
  # Build (no push) + Push job
  # -----------------------------
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.compute.outputs.short_sha }}
      env_name:  ${{ steps.compute.outputs.env_name }}
      image_tag: ${{ steps.meta.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      # Decide environment from branch and compute short SHA
      - name: Compute env + short SHA
        id: compute
        run: |
          REF="${GITHUB_REF#refs/heads/}"
          if [[ "$REF" == "main" ]]; then ENV=prod
          elif [[ "$REF" == "staging" || "$REF" == stg/* ]]; then ENV=stg
          else ENV=dev; fi
          echo "env_name=$ENV" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tags: <env>-<shortsha> + latest for dev only
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.compute.outputs.env_name }}-${{ steps.compute.outputs.short_sha }}
            # give "latest" only to dev env:
            type=raw,value=latest,enable=${{ steps.compute.outputs.env_name == 'dev' }}

      # 🔹 Build only (no push) — smoke-test Dockerfile
      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: ${{ env.IMAGE_NAME }}:ci-check
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      # 🔹 Push image with final tags
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

  # -----------------------------
  # Sonar (tests + coverage + gate)
  # -----------------------------
  sonar_scan:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pytest pytest-cov coverage

      # Disable OpenTelemetry during CI (no collector)
      - name: Test (pytest) + coverage
        env:
          OTEL_SDK_DISABLED: "true"
          OTEL_TRACES_EXPORTER: "none"
          OTEL_LOG_LEVEL: "error"
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=. --cov-branch --cov-report=xml

      - name: Ensure sonar-project.properties has coverage path
        run: |
          PROP_FILE="sonar-project.properties"
          if [ ! -f "$PROP_FILE" ]; then
            echo "sonar.projectKey=giropops-senhas" > "$PROP_FILE"
            echo "sonar.sources=." >> "$PROP_FILE"
          fi
          if grep -q '^sonar.python.coverage.reportPaths=' "$PROP_FILE"; then
            sed -i 's|^sonar.python.coverage.reportPaths=.*|sonar.python.coverage.reportPaths=coverage.xml|' "$PROP_FILE"
          else
            echo "sonar.python.coverage.reportPaths=coverage.xml" >> "$PROP_FILE"
          fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

      - name: Wait for Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # -----------------------------
  # Argo CD deployment
  # -----------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push, sonar_scan]
    if: ${{ needs.sonar_scan.result == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Compute env + tag + namespace + app name
        id: compute
        shell: bash
        run: |
          REF="${GITHUB_REF#refs/heads/}"
          if [[ "$REF" == "main" ]]; then ENV=prod
          elif [[ "$REF" == "staging" || "$REF" == stg/* ]]; then ENV=stg
          else ENV=dev; fi

          case "$ENV" in
            dev)  NS="dev-giropops-senhas";;
            stg)  NS="stg-giropops-senhas";;
            prod) NS="prd-giropops-senhas";;
          esac

          SHA7="${GITHUB_SHA::7}"
          TAG="${ENV}-${SHA7}"

          echo "env_name=$ENV"                  >> $GITHUB_OUTPUT
          echo "short_sha=$SHA7"                >> $GITHUB_OUTPUT
          echo "image_tag=$TAG"                 >> $GITHUB_OUTPUT
          echo "namespace=$NS"                  >> $GITHUB_OUTPUT
          echo "app_name=giropops-senhas-$ENV"  >> $GITHUB_OUTPUT

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          install -m 755 argocd /usr/local/bin/argocd
          argocd version --client

      - name: ArgoCD login (normalize endpoint)
        env:
          ARGOCD_SERVER:   ${{ secrets.ARGOCD_SERVER }}   # http(s)://host or host[:port]
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        shell: bash
        run: |
          set -euo pipefail
          RAW="${ARGOCD_SERVER}"; SCHEME="https"; HOSTPORT="$RAW"
          if [[ "$RAW" =~ ^https:// ]]; then SCHEME="https"; HOSTPORT="${RAW#https://}";
          elif [[ "$RAW" =~ ^http:// ]]; then SCHEME="http"; HOSTPORT="${RAW#http://}"; fi
          HOSTPORT="${HOSTPORT%/}"
          if [[ "$HOSTPORT" != *:* ]]; then
            [[ "$SCHEME" == "http" ]] && HOSTPORT="${HOSTPORT}:80" || HOSTPORT="${HOSTPORT}:443"
          fi
          FLAGS=( --grpc-web )
          [[ "$SCHEME" == "http" ]] && FLAGS+=( --plaintext ) || FLAGS+=( --insecure )
          echo "Login $HOSTPORT ($SCHEME) flags: ${FLAGS[*]}"
          argocd login "$HOSTPORT" "${FLAGS[@]}" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD"

      - name: Create or update Application (per env) with CreateNamespace=true
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        shell: bash
        run: |
          set -euo pipefail
          APP="${{ steps.compute.outputs.app_name }}"
          NS="${{ steps.compute.outputs.namespace }}"
          TAG="${{ steps.compute.outputs.image_tag }}"
          ENV_NAME="${{ steps.compute.outputs.env_name }}"
          IMAGE_REPO="${IMAGE_NAME}"
          IMAGE_FULL="${IMAGE_REPO}:${TAG}"

          # If you add per-env values files later, add:
          #   --values kubernetes/chart/values-${ENV_NAME}.yaml
          # to BOTH create and set commands.

          if ! argocd app get "$APP" >/dev/null 2>&1; then
            argocd app create "$APP" \
              --repo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" \
              --revision "$GITHUB_REF_NAME" \
              --path kubernetes/chart \
              --dest-server "https://kubernetes.default.svc" \
              --dest-namespace "$NS" \
              --sync-option CreateNamespace=true \
              --sync-policy automated --auto-prune \
              \
              --helm-set environment="$ENV_NAME" \
              --helm-set-string app.image.repository="$IMAGE_REPO" \
              --helm-set-string app.image.tag="$TAG" \
              --helm-set-string deployments.giropops-senhas.image="$IMAGE_FULL" \
              --helm-set-string deployments.giropops-senhas.labels.env="$ENV_NAME"
          else
            argocd app set "$APP" \
              --revision "$GITHUB_REF_NAME" \
              --dest-namespace "$NS" \
              --sync-option CreateNamespace=true \
              \
              -p environment="$ENV_NAME" \
              -p app.image.repository="$IMAGE_REPO" \
              -p app.image.tag="$TAG" \
              -p deployments.giropops-senhas.image="$IMAGE_FULL" \
              -p deployments.giropops-senhas.labels.env="$ENV_NAME"
          fi

      - name: Sync & wait
        run: |
          APP="${{ steps.compute.outputs.app_name }}"
          argocd app sync "$APP" --prune --timeout 600
          argocd app wait "$APP" --health --sync --timeout 600
